

services:
  webapp:
    image: mutlukoyunoglu
    expose:
      - "80"

  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    depends_on:
      - webapp
    ports:
      - "8081:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
